categories: [Metagenomics]
description: 'Suite for metabarcoding analysis'
homepage_url: http://frogs.toulouse.inrae.fr/
long_description: 'This is FROGS Galaxy Wrappers
FROGS is a workflow designed to produce an ASV count matrix from high depth sequencing amplicon data. Adviced : reorder integrated_tool_panel.xml as indicated here : https://github.com/geraldinepascal/FROGS-wrappers#simplest-way 
'
name: frogs
owner: oinizan
remote_repository_url: https://github.com/geraldinepascal/FROGS-wrappers/
