categories:
  - Data Managers
description: frogs data manager
name: frogs_data_manager
owner: frogs
include: 
  - data_manager/FROGS_data_manager.py
  - data_manager/FROGS_data_manager.xml
  - tool-data/frogs_db.loc.sample
  - tool-data/HVL_db.loc.sample
  - tool-data/phiX_db.loc.sample
  - data_manager_conf.xml
  - README.md
  - tool_data_table_conf.xml.sample
  - tool_dependencies.xml
